import productImage1 from "@/assets/img/product/20.png";

const getAllFeatues = () => {
  const features = [
    {
      id: 1,
      title: "Professional Installation",
      img: <i className="icon-mechanic"></i>,
      path: "/services",
      desc: "Expert delivery and installation of all types of fitness equipment with trained certified professionals ensuring safe setup and optimal placement.",
      bg: "dark",
      bgImg: null,
    },
    {
      id: 2,
      title: "Equipment Maintenance",
      img: <i className="icon-maintenance"></i>,
      path: "/team",
      desc: "Comprehensive maintenance and servicing to keep your fitness equipment running at maximum capability with regular inspections and repairs.",
      bg: "secondary",
      bgImg: productImage1,
    },
    {
      id: 3,
      title: "Equipment Moving",
      img: <i className="icon-arrows"></i>,
      path: "/services/1",
      desc: "Safe and efficient relocation of fitness equipment with professional handling to protect your investment and facility during every move.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 4,
      title: "All Equipment Brands",
      img: <i className="icon-options"></i>,
      path: "/services",
      desc: "Experienced with all major fitness equipment brands and models, from treadmills and ellipticals to strength training and specialty equipment.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 5,
      title: "Certified Professionals",
      img: <i className="icon-award"></i>,
      path: "/team",
      desc: "Industry-certified insured and bonded staff with 15+ years of experience, veteran-owned and operated with commitment to excellence in every service.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 6,
      title: "Professional Cleaning",
      img: <i className="icon-soap"></i>,
      path: "/services",
      desc: "Deep cleaning and sanitization services for your fitness equipment to maintain hygiene standards and extend equipment lifespan for maximum value.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 7,
      title: "Space Planning",
      img: <i className="icon-location"></i>,
      path: "/appointment",
      desc: "Strategic equipment placement and space optimization consulting to maximize your fitness facility layout and workflow efficiency for better results.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 8,
      title: "Concierge Planned Maintenance",
      img: <i className="icon-maintenance-1"></i>,
      path: "/services",
      desc: "Our signature program for proactive equipment care with monthly scheduled visits including detailed inspections cleaning and calibration for all covered machines.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 9,
      title: "Warranty Facilitation With OEM",
      img: <i className="icon-tag"></i>,
      path: "/services",
      desc: "We manage manufacturer warranty claims on your behalf from parts ordering to logistics and coordination ensuring every warranty issue is resolved quickly.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 10,
      title: "Non Warranty Repair Work",
      img: <i className="icon-repair-1"></i>,
      path: "/services",
      desc: "When equipment is out of warranty our certified technicians respond fast with service level agreements ensuring priority handling for critical repairs.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 11,
      title: "Delivery and Installation",
      img: <i className="icon-mechanic"></i>,
      path: "/services",
      desc: "Professional delivery and setup for new facilities remodels or equipment refresh projects completed with precision testing and final verification checks.",
      bg: "white",
      bgImg: null,
    },


    // Adding Below this line for Technology page

    {
      id: 12,
      title: "Scan the Code",
      img: <i className="fas fa-qrcode"></i>,
      path: "/services",
      desc: "Our built-in QR system allows quick issue reporting—simply scan the code on the machine and send your request instantly.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 13,
      title: "Submit a Request",
      img: <i className="fas fa-mail-reply"></i>,
      path: "/services",
      desc: "Our quick-submit tool allows you to attach a brief note, photo, or description and send it in seconds.",
      bgImg: null,
    },
    {
      id: 14,
      title: "Track Progress",
      img: <i className="fas fa-arrow-trend-up"></i>,
      path: "/services",
      desc: "Our live tracking system shows your service request progress from received to assigned to completed.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 15,
      title: "Get Notified",
      img: <i className="fas fa-bell"></i>,
      path: "/services",
      desc: "Stay informed with updates when a technician is scheduled or work is completed.",
      bg: "white",
      bgImg: null,
    },
    {
      id: 16,
      title: "Stay Ahead",
      img: <i className="fas fa-calendar-plus"></i>,
      path: "/services",
      desc: "Prevent downtime with planned maintenance programs that address issues before they happen.",
      bg: "white",
      bgImg: null,
    },
  ];

  return features;
};

export default getAllFeatues;
